version: "3.8"

services:
  # Webex Bot Service
  webex-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jaguar-webex-bot
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - bot-network

  # Ngrok Service
  ngrok:
    image: ngrok/ngrok:3-alpine
    container_name: jaguar-ngrok
    restart: unless-stopped
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command:
      - "http"
      - "--domain=${NGROK_DOMAIN}"
      - "webex-bot:3000"
    ports:
      - "4040:4040" # Ngrok web interface
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge
