version: "3.8"

services:
  # Webex Bot Service
  webex-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jaguar-webex-bot
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    ports:
      - "3000:3000"
    networks:
      - bot-network

  # Ngrok Service
  ngrok:
    image: ngrok/ngrok:3-alpine
    container_name: jaguar-ngrok
    restart: unless-stopped
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command:
      - "http"
      - "--domain=${NGROK_DOMAIN}"
      - "webex-bot:3000"
    ports:
      - "4040:4040" # Ngrok web interface
    networks:
      - bot-network

  # PostgreSQL Service
  postgres:
    image: postgres:latest
    container_name: jaguar-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=your_bot_database_name
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

networks:
  bot-network:
    driver: bridge
